
name: Manual Test Release to TestPyPI with uv (Token Auth)

on:
  workflow_dispatch:

jobs:
  test_deploy:
    runs-on: ubuntu-latest
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/${{ github.repository }} 


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        env:
          PATH: ~/.cargo/bin:$PATH 

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - name: Build Source and Wheel Distributions with uv
        run: uv build --sdist --wheel --out-dir dist

      - name: Publish to TestPyPI using uv with Token
        run: uv publish --publish-url https://test.pypi.org/legacy/ --token ${{ secrets.PYPI_TEST_TOKEN }}
